name: Build master

on: [push, pull_request]
jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "4.14.2"

      - name: Install dependencies
        run: |
          opam init
          opam update
          make deps
          opam install --yes . --deps-only --with-test --yes

      - name: Check formatting
        run: |
          eval $(opam env)
          dune build @fmt --profile=release

      - name: Run tests
        run: |
          eval $(opam env)
          dune runtest --profile=release
